### PR TITLE
ppx_tools for modular-implicits compiler

### PR DESCRIPTION
**Pull request by Aaylor**
Some changes were needed for the modular-implicits compiler.
(https://github.com/ocamllabs/ocaml-modular-implicits)  

Is there any possibility to create a branch, keeping compatibility, 
and sending a special version of ppx_tools for this compiler ?

### CODE REVIEW

**Comment by alainfrisch** [comment]
The branch exist, it is https://github.com/Aaylor/ppx_tools !  Since I assume you work on ocaml-modular-implicits yourself (or are just interested to have ppx_tools work on it), it makes sense that you maintain the branch on your side.  I don't know what needs to be done on the OPAM side to allow testing easily ocaml-modular-implicits with modified packages.

Concerning the pull request itself, it seems that part of it is to undo the changes required between 4.02 and 4.03 related to inline records.  If you rebase the changes to the version of ppx_tools of 4.02, that should reduce the diff quite a bit.

**Comment by Aaylor** [comment]
OPAM doesn't seems to allow multiple repository for different version. The only way I found is to create a new OPAM repository with the correct compiler restriction.

As I don't work on the modular-implicits compiler itself, the best solution, I guess, will be to rebase to the version 4.02 of ppx_tools.

Is this a solution to create a new opam repository (with name like "ppx_tools_modular_implcits" for example) ?
Should we close this pull request ?

**Comment by alainfrisch** [comment]
I'm not really familiar with OPAM, so I don't really know what to do (but certainly the fact that the patched branch is hosted by my github account or yours doesn't matter).  I suggest you contact OPAM people to get advice on how to proceed.

**Comment by Aaylor** [comment]
I've just ask on the opam repository.
An other idea (more painful, and i'm not really sure it will work correctly), should be to use [cppo](https://github.com/mjambon/cppo) package to handle different version of the compilers using preprocessing. But I don't really like the idea of using a preprocessing tool to compile an another preprocessing tool...

**Comment by alainfrisch** [comment]
I'm trying to avoid dependencies as much as possible for ppx_tools.  And it also would be quite weird to add support in the main code base support not only for several official versions of OCaml, but also experimental ones.

**Pull request closed without merging**
