### PR TITLE
2016 06 26 compat

### PR DESCRIPTION
**Pull request by lefessan**
Provide compatibility from 4.02.0 to 4.03.0 using `ocp-pp` (included in `ocp-build`)

### CODE REVIEW

**Comment by Drup** [comment]
If we are going to use a pre-processor, we should use cppo.

**Comment by alainfrisch** [comment]
I prefer to maintain different branches for multiple versions of OCaml rather than add more external dependencies for such a core component.

**Comment by lefessan** [comment]
Then, may I create a package `ocp-ppx-tools` with this fork ? Right now, each version of `ppx_tools` on OPAM is only compatible with one version of OCaml, which limits portability of packages across versions.

**Comment by alainfrisch** [comment]
If you depend on "ppx_tools >= 5.0", it will work for both 4.02 and 4.03 (resolving to 5.0+4.02.0 or 5.0+4.03.0).  This is what sedlex 1.99.3 does.

**Pull request closed without merging**
