### PR TITLE
Locations in Ast_convenience helpers.

### PR DESCRIPTION
**Pull request by aantron**
I suggest adding `?loc` (and maybe `?attr`) arguments to most helpers in `Ast_convenience`, in the style of `Ast_helper`. Without the ability to specify locations, the practical usefulness of `Ast_convenience` is considerably restricted.

If you agree in principle, I will add optional locations and attributes to all helpers for which they make sense, and make the counterpart 4.02 patch.

### CODE REVIEW

**Comment by Drup** [comment]
I would like that as well, I find the location-by-side-effect style very annoying in practice.

**Comment by alainfrisch** [comment]
Ok for adding ?loc arguments (and ?attr if you wish).

**Comment by aantron** [comment]
Added `?loc` and `?attr` to all the construction helpers, except `sequence`. For `sequence`, do you think we should:

- Take the locations from the expression list?
- Give the caller the ability to pass in a list of locations?
- Give the caller the ability to pass one location, and use that for each of the sequence expressions?

There is a similar question for `list`. For `list`, for now, I just used the same location for all the `cons` operations and `nil`.

And again a similar question for the labels in a record expression.

Will make the 4.02 version when we decide these.

**Comment by Drup** [comment]
About list/sequence, the location is about the list itself, not the individual elements. It's fine to use one location for the whole thing. So, option 3.

**Comment by aantron** [comment]
For `list`, it's about the locations of the cons and nil expressions, not the location of the list itself nor the individual elements. However, it makes enough sense to just use one location for the whole thing. For sequence, it makes less sense, since sequences are binary and there isn't a syntactic sugar for n-ary sequences like there is for lists. However, it still seems reasonable enough.

Out of curiosity, does anyone know off the top of their head what the compiler generates? I would guess that each generated location includes the locations of the nested expressions as subspans. So, locations in a list expand to the left, and locations in nested sequences expand to the right, until the outer one includes the whole list/sequence (I'm not proposing to implement this).

**Comment by Drup** [comment]
I think this is ready now. @alainfrisch ?

**Comment by aantron** [comment]
Indeed. 👉 @alainfrisch

**Comment by alainfrisch** [comment]
Thanks!

**Pull request merged**
