### PR TITLE
Restore compatibility with 4.03

### PR DESCRIPTION
**Pull request by whitequark**
If keeping compatibility with older versions of OCaml is desirable, I think [cppo](http://mjambon.com/cppo.html) is a good choice.

### CODE REVIEW

**Comment by Drup** [comment]
I did https://github.com/Drup/ppx_tools/tree/4.03.0, which correspond to what I understood of the consensus.

**Comment by alainfrisch** [comment]
Thanks!

I'm wondering whether we should keep the previous interface for Ast_convenience.lam with a string label and add another version taking a arg_label argument, or just switch to arg_label (i.e. do not attempt to preserve backward compatibility).

Opinions?

**Comment by alainfrisch** [comment]
@Drup:  it seems we could get rid of OCAML and OCAML_VERSION.

**Comment by whitequark** [comment]
Be consistent and break it.

@Drup Maybe you should rebase your changes without my commits?

**Pull request closed without merging**
